Clase RepartidorDao
acasella03/Shopper2 pull request #13
Opened 2023-05-22 16:08 UTC by JorgeAmestoy

Hola @acasella03 , en esta nueva rama he creado el paquete <b>controlador</b> con la clase <b>RepartidorDao</b> y el método buscar para cuando hagamos una consulta en la base de datos.
Échale un ojo cuando puedas.

2023-05-22 21:11 UTC, acasella03 commented on src/com/shopper2/modelo/repartidores/Repartidor.java
> +    public void setCodr(int codr) {
Genial que agregaste los setter correspondientes en ésta clase.

2023-05-22 21:54 UTC, acasella03 requested changes
Aún no puedes hacer merge

2023-05-22 21:54 UTC, acasella03 commented on src/com/shopper2/controlador/RepartidorDao.java
> +public class RepartidorDao {
Está muy bien, pero vamos a agregar el método de conexión por ahora a todos los DAO incluyendo éste, aunque sea redundante, luego lo convertimos en un Singleton.

2023-05-23 07:35 UTC, JorgeAmestoy commented on src/com/shopper2/controlador/RepartidorDao.java
> +public class RepartidorDao {
@acasella03 ya añadi el método conexión

2023-05-23 07:36 UTC, merged